SELECT * FROM edu.jnl10_acnt ja ;

-- Å×ÀÌºí comment
SELECT N.NSPNAME, C.RELNAME, OBJ_DESCRIPTION(C.OID) 
FROM PG_CATALOG.PG_CLASS C INNER JOIN PG_CATALOG.PG_NAMESPACE N ON C.RELNAMESPACE=N.OID 
WHERE C.RELKIND = 'r'
AND NSPNAME = 'edu'
;
AND RELNAME = 'jnl10_acnt'


SELECT * 
FROM edu.jnl11_repr_acnt jra ;